export const initialState = {
  partials: {
    allUfs: [
      'BR',
      'RJ',
      'AC',
      'AL',
      'AP',
      'AM',
      'BA',
      'CE',
      'DF',
      'ES',
      'GO',
      'MA',
      'MT',
      'MS',
      'MG',
      'PA',
      'PB',
      'PR',
      'PE',
      'PI',
      'RN',
      'RS',
      'RO',
      'RR',
      'SC',
      'SP',
      'SE',
      'TO',
    ],
    byUf: {
      BR: { name: 'Brasil', uf: 'BR', current: {}, history: [] },
      RJ: { name: 'Rio de Janeiro', uf: 'RJ', current: {}, history: [] },
      AC: { name: 'Acre', uf: 'AC', current: {}, history: [] },
      AL: { name: 'Alagoas', uf: 'AL', current: {}, history: [] },
      AP: { name: 'Amapá', uf: 'AP', current: {}, history: [] },
      AM: { name: 'Amazonas', uf: 'AM', current: {}, history: [] },
      BA: { name: 'Bahia', uf: 'BA', current: {}, history: [] },
      CE: { name: 'Ceará', uf: 'CE', current: {}, history: [] },
      DF: { name: 'Distrito Federal', uf: 'DF', current: {}, history: [] },
      ES: { name: 'Espírito Santo', uf: 'ES', current: {}, history: [] },
      GO: { name: 'Goiás', uf: 'GO', current: {}, history: [] },
      MA: { name: 'Maranhão', uf: 'MA', current: {}, history: [] },
      MT: { name: 'Mato Grosso', uf: 'MT', current: {}, history: [] },
      MS: { name: 'Mato Grosso do Sul', uf: 'MS', current: {}, history: [] },
      MG: { name: 'Minas Gerais', uf: 'MG', current: {}, history: [] },
      PA: { name: 'Pará', uf: 'PA', current: {}, history: [] },
      PB: { name: 'Paraíba', uf: 'PB', current: {}, history: [] },
      PR: { name: 'Paraná', uf: 'PR', current: {}, history: [] },
      PE: { name: 'Pernambuco', uf: 'PE', current: {}, history: [] },
      PI: { name: 'Piauí', uf: 'PI', current: {}, history: [] },
      RN: { name: 'Rio Grande do Norte', uf: 'RN', current: {}, history: [] },
      RS: { name: 'Rio Grande do Sul', uf: 'RS', current: {}, history: [] },
      RO: { name: 'Rondônia', uf: 'RO', current: {}, history: [] },
      RR: { name: 'Roraima', uf: 'RR', current: {}, history: [] },
      SC: { name: 'Santa Catarina', uf: 'SC', current: {}, history: [] },
      SP: { name: 'São Paulo', uf: 'SP', current: {}, history: [] },
      SE: { name: 'Sergipe', uf: 'SE', current: {}, history: [] },
      TO: { name: 'Tocantins', uf: 'TO', current: {}, history: [] },
    },
  },
}
